ALTER TABLE clients
	ADD COLUMN IF NOT EXISTS assigned_agent_id VARCHAR(64) NOT NULL DEFAULT 'usr_unknown',
	ADD COLUMN IF NOT EXISTS identity_verification_status VARCHAR(20) NOT NULL DEFAULT 'unverified',
	ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

