apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: agent-service
    newTag: dev
  - name: client-service
    newTag: dev
  - name: log-service
    newTag: dev
  - name: transaction-service
    newTag: dev
  - name: crm-ui
    newTag: dev
patches:
  - path: client-service-patch.yaml
    target:
      kind: Deployment
      name: client-service
  - path: log-service-patch.yaml
    target:
      kind: Deployment
      name: log-service
  - path: transaction-service-patch.yaml
    target:
      kind: Deployment
      name: transaction-service
labels:
  - pairs:
      app.kubernetes.io/part-of: crm-backend
      app.kubernetes.io/environment: dev
    includeSelectors: true
    includeTemplates: true

