apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: transaction-service
          env:
            - name: CLIENT_SERVICE_URL
              value: http://client-service.dev.svc.cluster.local

