CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(320) NOT NULL,
	role VARCHAR(32) NOT NULL,
	status VARCHAR(32) NOT NULL,
	password_hash VARCHAR(256) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
	token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	token_hash VARCHAR(64) NOT NULL,
	user_id BIGINT NOT NULL,
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
	CONSTRAINT fk_refresh_tokens_user
		FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id
	ON refresh_tokens(user_id);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at
	ON refresh_tokens(expires_at);

INSERT INTO users (user_id, first_name, last_name, email, role, status, password_hash, created_at, updated_at)
VALUES (0, 'Super', 'Admin', 'superAdmin@crm.com', 'super_admin', 'active', '$argon2id$v=19$m=19456,t=2,p=1$MzU5MjA0ZDM3YTUxYTc0YjVkYTdiMjhkY2Q3NTEzOGU$yZ+HQfCopGe7HBYVPP2cVURyi2zs8zL1VOFQqhRtrTg', NOW(), NOW())
ON CONFLICT DO NOTHING;
