CREATE TABLE IF NOT EXISTS agent_users (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(320) NOT NULL,
	role VARCHAR(32) NOT NULL,
	status VARCHAR(32) NOT NULL,
	password_hash VARCHAR(256) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT uk_agent_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS agent_refresh_tokens (
	token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	token_hash VARCHAR(64) NOT NULL,
	user_id BIGINT NOT NULL,
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT uk_agent_refresh_tokens_hash UNIQUE (token_hash),
	CONSTRAINT fk_agent_refresh_tokens_user
		FOREIGN KEY (user_id) REFERENCES agent_users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_refresh_tokens_user_id
	ON agent_refresh_tokens(user_id);

CREATE INDEX IF NOT EXISTS idx_agent_refresh_tokens_expires_at
	ON agent_refresh_tokens(expires_at);
