alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30082

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 30083
