apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - agent-service-deployment.yaml
  - agent-service-service.yaml
  - client-service-deployment.yaml
  - client-service-service.yaml
  - log-service-deployment.yaml
  - log-service-service.yaml
  - transaction-service-mock-sftp-configmap.yaml
  - transaction-service-deployment.yaml
  - transaction-service-service.yaml
  - ingress.yaml

