apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - agent-deployment.yaml
  - agent-service.yaml
  - client-deployment.yaml
  - client-service.yaml
  - log-deployment.yaml
  - log-service.yaml
  - transaction-mock-sftp-configmap.yaml
  - transaction-deployment.yaml
  - transaction-service.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

