apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - user-service-deployment.yaml
  - user-service-service.yaml
  - client-service-deployment.yaml
  - client-service-service.yaml
  - log-service-deployment.yaml
  - log-service-service.yaml
  - transactions-service-mock-sftp-configmap.yaml
  - transactions-service-deployment.yaml
  - transactions-service-service.yaml
  - ingress.yaml
