apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-mock-sftp
  namespace: dev
data:
  transactions.csv: |
    clientId,transaction,amount,date,status
    clt_01HZY9T3W4D7Y4W7ZB2X7MZ8QK,D,1200.50,2026-02-01,Completed
    clt_01HZY9T3W4D7Y4W7ZB2X7MZ8QK,W,250.00,2026-02-02,Pending
    clt_01HZY9T3W4D7Y4W7ZB2X7MZ8QK,D,75.25,2026-02-03,Failed

