apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - ../../base

images:
  - name: agent
    newTag: dev
  - name: client
    newTag: dev
  - name: log
    newTag: dev
  - name: transaction
    newTag: dev
  - name: crm-ui
    newTag: dev

patches:
  - path: replicas.yaml
  - path: hpa-overrides.yaml
  - target:
      kind: Ingress
      name: backend-ingress
    path: ingress.yaml

