apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 2 * * *" # daily at 02:00
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: pg-backup
              image: postgres:16
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-postgresql
                      key: password
              command:
                - /bin/sh
                - -c
                - >
                  pg_dump
                  -h postgres-postgresql.dev.svc.cluster.local
                  -U cs301
                  cs301
                  > /backups/cs301-$(date +%Y%m%d%H%M%S).sql
              volumeMounts:
                - name: backup-volume
                  mountPath: /backups
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: postgres-backups
