CREATE TABLE transaction_import_batches (
    batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    requested_client_id VARCHAR(128),
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    total_records INTEGER NOT NULL,
    imported_records INTEGER NOT NULL,
    failed_records INTEGER NOT NULL,
    error_message VARCHAR(255)
);

CREATE TABLE transaction_records (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(128) NOT NULL,
    kind VARCHAR(8) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    date DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    imported_at TIMESTAMP WITH TIME ZONE,
    import_batch_id BIGINT,
    import_dedupe_key VARCHAR(64),
    CONSTRAINT fk_transaction_records_batch
        FOREIGN KEY (import_batch_id)
        REFERENCES transaction_import_batches(batch_id)
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX idx_transaction_records_import_dedupe_key
    ON transaction_records(import_dedupe_key);

CREATE INDEX idx_transaction_records_client_id ON transaction_records(client_id);
CREATE INDEX idx_transaction_records_date ON transaction_records(date);
CREATE INDEX idx_transaction_records_status ON transaction_records(status);
CREATE INDEX idx_transaction_records_import_batch_id ON transaction_records(import_batch_id);
