apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
  namespace: dev
type: Opaque
stringData:
  private.pem: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_PRIVATE_KEY
    -----END PRIVATE KEY-----
  public.pem: |
    -----BEGIN PUBLIC KEY-----
    REPLACE_WITH_PUBLIC_KEY
    -----END PUBLIC KEY-----
